"""
map É UMA FUNÇÃO QUE POSSIBILITA APLICAR OUTRA FUNÇÃO A CADA ELEMENTO DE UMA LISTA, SEM USAR
LAÇO DIRETAMENTE NO PROGRAMA PRINCIPAL OU FUNÇÃO.
NA ESTRUTURA DA FUNÇÃO MAP, TEMOS:
map(<função>,<lista>)
POR EXEMPLO, PARA DOBRAR CADA ELEMENTO DA LISTA

#FUNÇÃO
def dobra(x):
    return x*2

#PROGRAMA PRINCIPAL
a=[1,2,3,4,5,6]
b=map(dobra,a)
b=list(b)
print(b)

b RECEBE O ELEMENTO MAP (ITERATOR) GERADO PELA FUNÇÃO map, E PARA MOSTRÁ-LO NA TELA,
CONVERTEMOS ESSE ELEMENTO DE VOLTA PARA FUNÇÃO
"""
#FUNÇÃO
def dobra(x):
    return x*2

#PROGRAMA PRINCIPAL
a=[1,2,3,4,5,6]
b=map(dobra,a)
b=list(b)
print(b)